In [8]:
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 22 21:18:07 2018

@author: Adrian
"""

import numpy as np
from datetime import datetime, time
import _sqlite3
import pandas as pd
import json
import re


def db_to_csv(query):
    conn = _sqlite3.connect('2016_11.db')
    data = pd.read_sql_query(query, conn)
    data.to_csv('ads.csv',sep=';')
 
def photos_parser(photo_sizes):
    photo_sizes=photo_sizes.replace('""','"')
    data=json.loads(photo_sizes)
    num_of_photos=len(data)
    return(num_of_photos)

def num_of_photos(data):
    all_photos = data['photo_sizes'].apply(str)
    num_of_photos = []
    for i in range(len(all_photos)):
        try:
            num_of_photos.append(photos_parser(all_photos[i]))
        except:
            num_of_photos.append(0)
    return(pd.DataFrame({'num_of_photos': num_of_photos}))


def time_since_creation(data):
    time_since_creation = pd.DataFrame({"time_since_creation": (pd.to_datetime(data['sorting_date'])-pd.to_datetime(data['created_at_first'])).astype('timedelta64[h]')})
    time_since_creation[time_since_creation<0]=0
    return(time_since_creation)


def traffic_level(data):
    l = np.zeros(len(data))
    twos=np.array((pd.to_datetime(data['sorting_date']).dt.time >= time(18,00)) & (time(22,00) >= pd.to_datetime(data['sorting_date']).dt.time))
    l[twos]=2
    ones=np.array((pd.to_datetime(data['sorting_date']).dt.time >= time(8,00)) & (time(18,00) >= pd.to_datetime(data['sorting_date']).dt.time))
    l[ones]=1
    return(pd.DataFrame({'traffic_level': l}))

def params_parser(params):
    params = str(params)
    par_list=re.split("<=>|<br>", params)
    parsed_params=dict()
    if 'price' in par_list:
        par_list[par_list.index('price')] = "price_type"
    for i in range(0, int((len(par_list)/2))):
        parsed_params[par_list[2*i]]=par_list[2*i+1]
    return parsed_params

def params(data):
    price_type, price, state, Type = ([] for i in range(4))
    for i in range(len(data)):
        params = str(data['params'][i])
        par = params_parser(params)
        try:
            price_type.append(par['price_type'])
        except KeyError:
            price_type.append(0)
        try:
            price.append(par['price'])
        except KeyError:
            price.append(0)
        try:
            state.append(par['state'])
        except KeyError:
            state.append(0)
        try:
            Type.append(par['type'])
        except KeyError:
            Type.append(0)
    params = pd.DataFrame({'price_type': price_type,
                           'price': price,
                           'state': state,
                           'type': Type})
    return(params)
   
def promo_level(data):
    promo_lvl = np.zeros(len(data))
    promo_lvl[data['paidads_id_index']==3] = 1
    promo_lvl[data['paidads_id_index']==4] = 2
    promo_lvl[data['paidads_id_index']==85] = 3
    return(pd.DataFrame({'promotion_level':promo_lvl}))
    
def convert_data(df):
    params_df = params(df)
    df = pd.concat([df, params_df, time_since_creation(df), traffic_level(df), num_of_photos(df), promo_level(df)], axis=1)
    df = df.drop([ 'user_id', 'city_id', 'params', 'sorting_date', 'created_at_first', 'photo_sizes', 'paidads_valid_to', 'paidads_id_index'],1)
    df.to_csv('ads_new.csv',sep=';')
    return(df)
####################################################################

In [4]:
import boto3
import io
s3 = boto3.client('s3')
obj = s3.get_object(Bucket='2016-11', Key='user_and_city.csv')
df = pd.read_csv(io.BytesIO(obj['Body'].read()),sep=';',dtype='unicode')


obj = s3.get_object(Bucket='2016-11', Key='model_raw.csv')
df2 = pd.read_csv(io.BytesIO(obj['Body'].read()),sep=';',dtype='unicode')

obj = s3.get_object(Bucket='2016-11', Key='sorted_ad_hits.csv')
df3 = pd.read_csv(io.BytesIO(obj['Body'].read()),sep=';',dtype='unicode')

In [6]:
obj = s3.get_object(Bucket='2016-11', Key='sorted_empy_sessions.csv')
df4 = pd.read_csv(io.BytesIO(obj['Body'].read()),sep=';',dtype='unicode')

In [15]:
data = convert_data(df2)

In [16]:
df = pd.DataFrame({'city_ads':df['city_ads'], 'user_ads': df['user_ads']})
data = pd.concat([data, df, df3, df4],axis=1)
data.to_csv('data.csv',sep=';',index=False)

In [17]:
file = open('data.csv', 'rb')
s3.put_object(Bucket='2016-11', Key='data.csv', Body=file)

{'ETag': '"efb8a9c9b716104a935145015278eddc"',
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '0',
   'date': 'Sat, 24 Feb 2018 17:56:42 GMT',
   'etag': '"efb8a9c9b716104a935145015278eddc"',
   'server': 'AmazonS3',
   'x-amz-id-2': 'aa3Z/AZ/WIL3MQbqIXEvoa9uW1cha6bXVzDyoCnGR2/kiwCXut6izelynF4FoajvlSpc1bYPstI=',
   'x-amz-request-id': '1CD5612DD603FC10'},
  'HTTPStatusCode': 200,
  'HostId': 'aa3Z/AZ/WIL3MQbqIXEvoa9uW1cha6bXVzDyoCnGR2/kiwCXut6izelynF4FoajvlSpc1bYPstI=',
  'RequestId': '1CD5612DD603FC10',
  'RetryAttempts': 0}}

In [18]:
obj = s3.get_object(Bucket='2016-11', Key='data.csv')
df5 = pd.read_csv(io.BytesIO(obj['Body'].read()),sep=';',dtype='unicode')
print(df5)

                id region_id category_id subregion_id has_phone  \
0              148         1         753          194         1
1              484        17         642          273         0
2             1238         7        1155          381         0
3             3363         2          93          387         1
4             4418         1        1199          180         1
5             5619         7         235          136         1
6             6783        13        1407          236         1
7             8166         5         725          210         1
8             8963         8         230          211         0
9            17601         6         506          209         1
10           18169        12         506          175         0
11           20214         1         406          166         0
12           22456         3         642          112         1
13           24905        11         642          272         1
14           26106        17         734          226         1
15           29791        11         282          260         1
16           39304         8         506          311         1
17           41881         5         461           45         1
18           48761        17         235           38         1
19           51121        18         235            9         1
20           52574        14         734           43         1
21           53927         6         734          349         1
22           54663         2        1157          287         1
23           57816        11         714          260         1
24           59354         4         642          102         0
25           60344         6        1457           83         1
26           65228         4         734          162         0
27           65885         6        1161           83         1
28           70826         2         235          333         1
29           71135         3        1273          124         1
...            ...       ...         ...          ...       ...
999969  2147418547         6         231          353         1
999970  2147418562         5         243          290         1
999971  2147420640         6         451           48         1
999972  2147421449         7         292          136         1
999973  2147425938         6        1459          126         1
999974  2147426316         6         584          299         1
999975  2147430370         1         219          181         1
999976  2147432435        11         230          261         1
999977  2147439182        15         626          278         1
999978  2147442236         3         231          145         1
999979  2147442934         1        1195          304         1
999980  2147447275        17         761          128         1
999981  2147452540        18         230            9         1
999982  2147453827        12         406           85         1
999983  2147455249         1         224           96         1
999984  2147456174         6         642           74         1
999985  2147458298         6         734          214         1
999986  2147458559        14         224          171         1
999987  2147458692         4         642          102         1
999988  2147460472         7        1161          136         1
999989  2147463270        12         230          485         1
999990  2147463747         5         230          276         1
999991  2147465190         3         431          303         1
999992  2147465638        18         761          429         1
999993  2147466167         3         734           49         1
999994  2147468813         3         230          124         1
999995  2147470370        14         642           15         1
999996  2147470996        11         642           98         1
999997  2147479668         6         230          373         1
999998  2147481575         1         721          220         1

       private_business predict_replies predict_sold predict_views price  \
0               private               0            0             6    13
1               private               0            0             2    20
2               private               0            0            45   NaN
3              business               0            0             7    40
4              business               0            0            41   899
5               private               0            0             3    40
6               private               0            0             8    15
7               private               0            0            12    65
8               private               0            0             2    18
9              business               0            0            28    79
10              private               0            0            56   189
11              private               0            0            11    60
12              private               0            0            78    60
13              private               0            0            25    40
14              private               0            0             0    40
15              private               1            1            26    50
16             business               0            0             4    43
17             business               0            0             9   149
18              private               0            0             2    70
19              private               0            0             6    20
20              private               0            0             0    30
21              private               0            0             0    25
22              private               0            0             5    15
23              private               0            0            48   400
24              private               0            0             5    60
25              private               2            0            28    50
26              private               0            1             0    20
27              private               0            0            19    20
28             business               0            0           311   229
29              private               0            0            66    15
...                 ...             ...          ...           ...   ...
999969          private               0            0            92    80
999970          private               1            0           354   NaN
999971          private               0            0             5   100
999972          private               0            0             1    50
999973          private               0            0           146   800
999974          private               0            0             2    45
999975          private               0            0             1    40
999976          private               0            0            13    15
999977          private               0            0           114   150
999978          private               0            0             7    35
999979         business               0            0             2  11.9
999980          private               0            0            15   2.5
999981          private               0            0             8    20
999982          private               0            0             0    35
999983          private               0            0             0    50
999984          private               0            0             4    35
999985          private               0            0            48    70
999986          private               0            0             2   160
999987          private               0            0             0    20
999988          private               0            0             0     4
999989          private               0            0             2    12
999990         business               0            0             7    29
999991          private               0            0            47  1200
999992          private               0            0            10    25
999993          private               0            0             1    15
999994          private               0            0             3    15
999995          private               0            0             7    22
999996          private               0            0            19    30
999997         business               0            0             2    35
999998          private               0            0            21  1190

            ...       time_since_creation traffic_level num_of_photos  \
0           ...                    1473.0           2.0             2
1           ...                     680.0           1.0             3
2           ...                       0.0           1.0             4
3           ...                       0.0           1.0             1
4           ...                    2493.0           1.0             8
5           ...                     459.0           2.0             2
6           ...                       0.0           1.0             2
7           ...                       0.0           1.0             4
8           ...                       0.0           2.0             1
9           ...                       0.0           1.0             2
10          ...                    1341.0           0.0             7
11          ...                       0.0           0.0             2
12          ...                       0.0           1.0             1
13          ...                       0.0           1.0             3
14          ...                     429.0           1.0             1
15          ...                       0.0           1.0             2
16          ...                    1007.0           1.0             4
17          ...                       0.0           1.0             2
18          ...                       0.0           1.0             3
19          ...                       0.0           2.0             3
20          ...                       0.0           0.0             5
21          ...                     337.0           1.0             4
22          ...                     313.0           0.0             2
23          ...                       0.0           1.0             3
24          ...                     335.0           2.0             5
25          ...                    1032.0           1.0             0
26          ...                       0.0           0.0             3
27          ...                     318.0           0.0             3
28          ...                    2559.0           1.0             4
29          ...                       0.0           2.0             0
...         ...                       ...           ...           ...
999969      ...                    4489.0           2.0             6
999970      ...                     108.0           1.0             6
999971      ...                       0.0           0.0             3
999972      ...                       0.0           1.0             1
999973      ...                     339.0           1.0             7
999974      ...                       0.0           2.0             1
999975      ...                     363.0           2.0             2
999976      ...                       0.0           1.0             1
999977      ...                       0.0           1.0             5
999978      ...                       0.0           1.0             3
999979      ...                       0.0           1.0             1
999980      ...                       0.0           1.0             3
999981      ...                       0.0           2.0             3
999982      ...                       0.0           1.0             1
999983      ...                       0.0           2.0             3
999984      ...                     840.0           1.0             7
999985      ...                       0.0           0.0             5
999986      ...                       0.0           2.0             4
999987      ...                       0.0           2.0             1
999988      ...                   19678.0           1.0             1
999989      ...                       0.0           1.0             1
999990      ...                    1644.0           1.0             1
999991      ...                     337.0           0.0             6
999992      ...                    4569.0           2.0             0
999993      ...                       0.0           1.0             6
999994      ...                       0.0           1.0             1
999995      ...                   15623.0           1.0             4
999996      ...                       0.0           1.0             4
999997      ...                    1007.0           1.0             2
999998      ...                       0.0           1.0             1

       promotion_level city_ads user_ads        keys values        id.1  \
0                  0.0      809        6         148      2         148
1                  0.0       23       23         484     34         484
2                  0.0       10        1        1238      0        1238
3                  0.0      555       26        3363      4        3363
4                  0.0     3743        6        4418      8        4418
5                  0.0    25278        2        5619      0        5619
6                  0.0     1001        2        6783      1        6783
7                  0.0      471        6        8166      3        8166
8                  0.0     1817       11        8963      4        8963
9                  0.0     1063        4       17601     28       17601
10                 0.0     4994        8       18169      1       18169
11                 0.0      890        4       20214      0       20214
12                 0.0     4241        1       22456      5       22456
13                 0.0       79        5       24905      6       24905
14                 0.0     7540        1       26106      4       26106
15                 0.0    16853        2       29791      4       29791
16                 0.0     2844       83       39304      3       39304
17                 0.0    19087        2       41881      5       41881
18                 0.0        8        1       48761     28       48761
19                 0.0    11458        2       51121     40       51121
20                 0.0       25        6       52574    108       52574
21                 0.0     1431       11       53927      3       53927
22                 0.0    75750       10       54663      1       54663
23                 0.0    16853        1       57816      0       57816
24                 0.0    31762        2       59354     18       59354
25                 0.0    12345        1       60344      1       60344
26                 0.0       26       12       65228      2       65228
27                 0.0    12345       29       65885      8       65885
28                 0.0      562        1       70826      7       70826
29                 0.0     2857        1       71135      3       71135
...                ...      ...      ...         ...    ...         ...
999969             0.0     1064        1  2147418547      4  2147418547
999970             0.0       44        1  2147418562      1  2147418562
999971             0.0     7064        2  2147420640      2  2147420640
999972             0.0    25278        1  2147421449      2  2147421449
999973             0.0       32        1  2147425938      0  2147425938
999974             0.0       43        9  2147426316      0  2147426316
999975             0.0       32        1  2147430370      0  2147430370
999976             0.0     1301        5  2147432435     17  2147432435
999977             0.0     9705        6  2147439182      4  2147439182
999978             0.0      489        5  2147442236      0  2147442236
999979             0.0     1645       14  2147442934      1  2147442934
999980             0.0       13        2  2147447275      4  2147447275
999981             0.0    11458       11  2147452540     24  2147452540
999982             0.0     1733        5  2147453827      4  2147453827
999983             0.0     2086        2  2147455249      3  2147455249
999984             0.0     2851        3  2147456174      5  2147456174
999985             0.0     1879        3  2147458298     26  2147458298
999986             0.0     9529        7  2147458559      4  2147458559
999987             0.0    31762       10  2147458692      0  2147458692
999988             0.0    25278        1  2147460472      1  2147460472
999989             0.0      275       10  2147463270      3  2147463270
999990             0.0     1998       13  2147463747      4  2147463747
999991             0.0    30524        5  2147465190      0  2147465190
999992             0.0        2        1  2147465638      0  2147465638
999993             0.0       84        4  2147466167      0  2147466167
999994             0.0     2857       10  2147468813      5  2147468813
999995             0.0      459        2  2147470370      0  2147470370
999996             0.0     6075        8  2147470996      5  2147470996
999997             0.0      882       20  2147479668      6  2147479668
999998             0.0       29       10  2147481575      3  2147481575

       empty_sessions
0                8842
1                   0
2                   0
3                   0
4              105036
5                   0
6                   0
7               57374
8                   0
9                   0
10                  0
11                  0
12                  0
13                  0
14                  0
15                  0
16                  0
17                  0
18                  0
19                  0
20                  0
21                  0
22               8713
23                  0
24                  0
25                  0
26                  0
27               1596
28                  0
29              38412
...               ...
999969              0
999970          28616
999971              0
999972              0
999973              0
999974              0
999975              0
999976              0
999977              0
999978              0
999979           6306
999980              0
999981              0
999982              0
999983              0
999984              0
999985              0
999986              0
999987              0
999988           1596
999989              0
999990              0
999991              0
999992              0
999993              0
999994              0
999995              0
999996              0
999997              0
999998         113386

[999999 rows x 23 columns]

In [19]:
print(data)

                id region_id category_id subregion_id has_phone  \
0              148         1         753          194         1
1              484        17         642          273         0
2             1238         7        1155          381         0
3             3363         2          93          387         1
4             4418         1        1199          180         1
5             5619         7         235          136         1
6             6783        13        1407          236         1
7             8166         5         725          210         1
8             8963         8         230          211         0
9            17601         6         506          209         1
10           18169        12         506          175         0
11           20214         1         406          166         0
12           22456         3         642          112         1
13           24905        11         642          272         1
14           26106        17         734          226         1
15           29791        11         282          260         1
16           39304         8         506          311         1
17           41881         5         461           45         1
18           48761        17         235           38         1
19           51121        18         235            9         1
20           52574        14         734           43         1
21           53927         6         734          349         1
22           54663         2        1157          287         1
23           57816        11         714          260         1
24           59354         4         642          102         0
25           60344         6        1457           83         1
26           65228         4         734          162         0
27           65885         6        1161           83         1
28           70826         2         235          333         1
29           71135         3        1273          124         1
...            ...       ...         ...          ...       ...
999969  2147418547         6         231          353         1
999970  2147418562         5         243          290         1
999971  2147420640         6         451           48         1
999972  2147421449         7         292          136         1
999973  2147425938         6        1459          126         1
999974  2147426316         6         584          299         1
999975  2147430370         1         219          181         1
999976  2147432435        11         230          261         1
999977  2147439182        15         626          278         1
999978  2147442236         3         231          145         1
999979  2147442934         1        1195          304         1
999980  2147447275        17         761          128         1
999981  2147452540        18         230            9         1
999982  2147453827        12         406           85         1
999983  2147455249         1         224           96         1
999984  2147456174         6         642           74         1
999985  2147458298         6         734          214         1
999986  2147458559        14         224          171         1
999987  2147458692         4         642          102         1
999988  2147460472         7        1161          136         1
999989  2147463270        12         230          485         1
999990  2147463747         5         230          276         1
999991  2147465190         3         431          303         1
999992  2147465638        18         761          429         1
999993  2147466167         3         734           49         1
999994  2147468813         3         230          124         1
999995  2147470370        14         642           15         1
999996  2147470996        11         642           98         1
999997  2147479668         6         230          373         1
999998  2147481575         1         721          220         1

       private_business predict_replies predict_sold predict_views price  \
0               private               0            0             6    13
1               private               0            0             2    20
2               private               0            0            45
3              business               0            0             7    40
4              business               0            0            41   899
5               private               0            0             3    40
6               private               0            0             8    15
7               private               0            0            12    65
8               private               0            0             2    18
9              business               0            0            28    79
10              private               0            0            56   189
11              private               0            0            11    60
12              private               0            0            78    60
13              private               0            0            25    40
14              private               0            0             0    40
15              private               1            1            26    50
16             business               0            0             4    43
17             business               0            0             9   149
18              private               0            0             2    70
19              private               0            0             6    20
20              private               0            0             0    30
21              private               0            0             0    25
22              private               0            0             5    15
23              private               0            0            48   400
24              private               0            0             5    60
25              private               2            0            28    50
26              private               0            1             0    20
27              private               0            0            19    20
28             business               0            0           311   229
29              private               0            0            66    15
...                 ...             ...          ...           ...   ...
999969          private               0            0            92    80
999970          private               1            0           354
999971          private               0            0             5   100
999972          private               0            0             1    50
999973          private               0            0           146   800
999974          private               0            0             2    45
999975          private               0            0             1    40
999976          private               0            0            13    15
999977          private               0            0           114   150
999978          private               0            0             7    35
999979         business               0            0             2  11.9
999980          private               0            0            15   2.5
999981          private               0            0             8    20
999982          private               0            0             0    35
999983          private               0            0             0    50
999984          private               0            0             4    35
999985          private               0            0            48    70
999986          private               0            0             2   160
999987          private               0            0             0    20
999988          private               0            0             0     4
999989          private               0            0             2    12
999990         business               0            0             7    29
999991          private               0            0            47  1200
999992          private               0            0            10    25
999993          private               0            0             1    15
999994          private               0            0             3    15
999995          private               0            0             7    22
999996          private               0            0            19    30
999997         business               0            0             2    35
999998          private               0            0            21  1190

            ...       time_since_creation traffic_level num_of_photos  \
0           ...                    1473.0           2.0             2
1           ...                     680.0           1.0             3
2           ...                       0.0           1.0             4
3           ...                       0.0           1.0             1
4           ...                    2493.0           1.0             8
5           ...                     459.0           2.0             2
6           ...                       0.0           1.0             2
7           ...                       0.0           1.0             4
8           ...                       0.0           2.0             1
9           ...                       0.0           1.0             2
10          ...                    1341.0           0.0             7
11          ...                       0.0           0.0             2
12          ...                       0.0           1.0             1
13          ...                       0.0           1.0             3
14          ...                     429.0           1.0             1
15          ...                       0.0           1.0             2
16          ...                    1007.0           1.0             4
17          ...                       0.0           1.0             2
18          ...                       0.0           1.0             3
19          ...                       0.0           2.0             3
20          ...                       0.0           0.0             5
21          ...                     337.0           1.0             4
22          ...                     313.0           0.0             2
23          ...                       0.0           1.0             3
24          ...                     335.0           2.0             5
25          ...                    1032.0           1.0             0
26          ...                       0.0           0.0             3
27          ...                     318.0           0.0             3
28          ...                    2559.0           1.0             4
29          ...                       0.0           2.0             0
...         ...                       ...           ...           ...
999969      ...                    4489.0           2.0             6
999970      ...                     108.0           1.0             6
999971      ...                       0.0           0.0             3
999972      ...                       0.0           1.0             1
999973      ...                     339.0           1.0             7
999974      ...                       0.0           2.0             1
999975      ...                     363.0           2.0             2
999976      ...                       0.0           1.0             1
999977      ...                       0.0           1.0             5
999978      ...                       0.0           1.0             3
999979      ...                       0.0           1.0             1
999980      ...                       0.0           1.0             3
999981      ...                       0.0           2.0             3
999982      ...                       0.0           1.0             1
999983      ...                       0.0           2.0             3
999984      ...                     840.0           1.0             7
999985      ...                       0.0           0.0             5
999986      ...                       0.0           2.0             4
999987      ...                       0.0           2.0             1
999988      ...                   19678.0           1.0             1
999989      ...                       0.0           1.0             1
999990      ...                    1644.0           1.0             1
999991      ...                     337.0           0.0             6
999992      ...                    4569.0           2.0             0
999993      ...                       0.0           1.0             6
999994      ...                       0.0           1.0             1
999995      ...                   15623.0           1.0             4
999996      ...                       0.0           1.0             4
999997      ...                    1007.0           1.0             2
999998      ...                       0.0           1.0             1

        promotion_level  city_ads  user_ads        keys values          id  \
0                   0.0       809         6         148      2         148
1                   0.0        23        23         484     34         484
2                   0.0        10         1        1238      0        1238
3                   0.0       555        26        3363      4        3363
4                   0.0      3743         6        4418      8        4418
5                   0.0     25278         2        5619      0        5619
6                   0.0      1001         2        6783      1        6783
7                   0.0       471         6        8166      3        8166
8                   0.0      1817        11        8963      4        8963
9                   0.0      1063         4       17601     28       17601
10                  0.0      4994         8       18169      1       18169
11                  0.0       890         4       20214      0       20214
12                  0.0      4241         1       22456      5       22456
13                  0.0        79         5       24905      6       24905
14                  0.0      7540         1       26106      4       26106
15                  0.0     16853         2       29791      4       29791
16                  0.0      2844        83       39304      3       39304
17                  0.0     19087         2       41881      5       41881
18                  0.0         8         1       48761     28       48761
19                  0.0     11458         2       51121     40       51121
20                  0.0        25         6       52574    108       52574
21                  0.0      1431        11       53927      3       53927
22                  0.0     75750        10       54663      1       54663
23                  0.0     16853         1       57816      0       57816
24                  0.0     31762         2       59354     18       59354
25                  0.0     12345         1       60344      1       60344
26                  0.0        26        12       65228      2       65228
27                  0.0     12345        29       65885      8       65885
28                  0.0       562         1       70826      7       70826
29                  0.0      2857         1       71135      3       71135
...                 ...       ...       ...         ...    ...         ...
999969              0.0      1064         1  2147418547      4  2147418547
999970              0.0        44         1  2147418562      1  2147418562
999971              0.0      7064         2  2147420640      2  2147420640
999972              0.0     25278         1  2147421449      2  2147421449
999973              0.0        32         1  2147425938      0  2147425938
999974              0.0        43         9  2147426316      0  2147426316
999975              0.0        32         1  2147430370      0  2147430370
999976              0.0      1301         5  2147432435     17  2147432435
999977              0.0      9705         6  2147439182      4  2147439182
999978              0.0       489         5  2147442236      0  2147442236
999979              0.0      1645        14  2147442934      1  2147442934
999980              0.0        13         2  2147447275      4  2147447275
999981              0.0     11458        11  2147452540     24  2147452540
999982              0.0      1733         5  2147453827      4  2147453827
999983              0.0      2086         2  2147455249      3  2147455249
999984              0.0      2851         3  2147456174      5  2147456174
999985              0.0      1879         3  2147458298     26  2147458298
999986              0.0      9529         7  2147458559      4  2147458559
999987              0.0     31762        10  2147458692      0  2147458692
999988              0.0     25278         1  2147460472      1  2147460472
999989              0.0       275        10  2147463270      3  2147463270
999990              0.0      1998        13  2147463747      4  2147463747
999991              0.0     30524         5  2147465190      0  2147465190
999992              0.0         2         1  2147465638      0  2147465638
999993              0.0        84         4  2147466167      0  2147466167
999994              0.0      2857        10  2147468813      5  2147468813
999995              0.0       459         2  2147470370      0  2147470370
999996              0.0      6075         8  2147470996      5  2147470996
999997              0.0       882        20  2147479668      6  2147479668
999998              0.0        29        10  2147481575      3  2147481575

       empty_sessions
0                8842
1                   0
2                   0
3                   0
4              105036
5                   0
6                   0
7               57374
8                   0
9                   0
10                  0
11                  0
12                  0
13                  0
14                  0
15                  0
16                  0
17                  0
18                  0
19                  0
20                  0
21                  0
22               8713
23                  0
24                  0
25                  0
26                  0
27               1596
28                  0
29              38412
...               ...
999969              0
999970          28616
999971              0
999972              0
999973              0
999974              0
999975              0
999976              0
999977              0
999978              0
999979           6306
999980              0
999981              0
999982              0
999983              0
999984              0
999985              0
999986              0
999987              0
999988           1596
999989              0
999990              0
999991              0
999992              0
999993              0
999994              0
999995              0
999996              0
999997              0
999998         113386

[999999 rows x 23 columns]

In [5]:
import pandas as pd
data = pd.read_csv('data.csv', sep=';',dtype='unicode')

In [7]:
data = data.rename(columns={'values':'hits'})

In [8]:
data = data.drop(['id','keys'],1)

In [9]:
cols = data.columns.tolist()

In [10]:
cols = set(cols)
cols

{'category_id',
 'city_ads',
 'empty_sessions',
 'has_phone',
 'hits',
 'id.1',
 'num_of_photos',
 'predict_replies',
 'predict_sold',
 'predict_views',
 'price',
 'price_type',
 'private_business',
 'promotion_level',
 'region_id',
 'state',
 'subregion_id',
 'time_since_creation',
 'traffic_level',
 'type',
 'user_ads'}

In [11]:
y= set(['predict_sold', 'predict_replies', 'predict_views'])

In [12]:
X= list(cols-y)
X

['city_ads',
 'price_type',
 'empty_sessions',
 'state',
 'promotion_level',
 'hits',
 'time_since_creation',
 'num_of_photos',
 'type',
 'private_business',
 'id.1',
 'region_id',
 'traffic_level',
 'user_ads',
 'has_phone',
 'price',
 'subregion_id',
 'category_id']

In [13]:
col_order = X + list(y)
col_order

['city_ads',
 'price_type',
 'empty_sessions',
 'state',
 'promotion_level',
 'hits',
 'time_since_creation',
 'num_of_photos',
 'type',
 'private_business',
 'id.1',
 'region_id',
 'traffic_level',
 'user_ads',
 'has_phone',
 'price',
 'subregion_id',
 'category_id',
 'predict_replies',
 'predict_views',
 'predict_sold']

In [14]:
data = data[col_order]

In [24]:
data.to_csv('train_data.csv', sep=';', index = False )

,id.1,time_since_creation,city_ads,private_business,region_id,promotion_level,state,hits,price,subregion_id,...,traffic_level,user_ads,empty_sessions,type,category_id,has_phone,price_type,predict_sold,predict_replies,predict_views
0,148,1473.0,809,private,1,0.0,used,2,13,194,...,2.0,6,8842,0,753,1,price,0,0,6
1,484,680.0,23,private,17,0.0,new,34,20,273,...,1.0,23,0,woman,642,0,price,0,0,2
2,1238,0.0,10,private,7,0.0,new,0,NaN,381,...,1.0,1,0,0,1155,0,exchange,0,0,45
3,3363,0.0,555,business,2,0.0,used,4,40,387,...,1.0,26,0,0,93,1,price,0,0,7
4,4418,2493.0,3743,business,1,0.0,used,8,899,180,...,1.0,6,105036,0,1199,1,price,0,0,41
5,5619,459.0,25278,private,7,0.0,0,0,40,136,...,2.0,2,0,0,235,1,price,0,0,3
6,6783,0.0,1001,private,13,0.0,new,1,15,236,...,1.0,2,0,0,1407,1,price,0,0,8
7,8166,0.0,471,private,5,0.0,used,3,65,210,...,1.0,6,57374,0,725,1,arranged,0,0,12
8,8963,0.0,1817,private,8,0.0,used,4,18,211,...,2.0,11,0,girl,230,0,price,0,0,2
9,17601,0.0,1063,business,6,0.0,new,28,79,209,...,1.0,4,0,unisex,506,1,price,0,0,28
10,18169,1341.0,4994,private,12,0.0,new,1,189,175,...,0.0,8,0,woman,506,0,price,0,0,56
11,20214,0.0,890,private,1,0.0,new,0,60,166,...,0.0,4,0,woman,406,0,price,0,0,11
12,22456,0.0,4241,private,3,0.0,used,5,60,112,...,1.0,1,0,woman,642,1,price,0,0,78
13,24905,0.0,79,private,11,0.0,new,6,40,272,...,1.0,5,0,woman,642,1,price,0,0,25
14,26106,429.0,7540,private,17,0.0,used,4,40,226,...,1.0,1,0,boy,734,1,price,0,0,0
15,29791,0.0,16853,private,11,0.0,new,4,50,260,...,1.0,2,0,0,282,1,price,1,1,26
16,39304,1007.0,2844,business,8,0.0,new,3,43,311,...,1.0,83,0,woman,506,1,price,0,0,4
17,41881,0.0,19087,business,5,0.0,new,5,149,45,...,1.0,2,0,0,461,1,price,0,0,9
18,48761,0.0,8,private,17,0.0,used,28,70,38,...,1.0,1,0,NaN,235,1,price,0,0,2
19,51121,0.0,11458,private,18,0.0,0,40,20,9,...,2.0,2,0,0,235,1,price,0,0,6
20,52574,0.0,25,private,14,0.0,used,108,30,43,...,0.0,6,0,boy,734,1,price,0,0,0
21,53927,337.0,1431,private,6,0.0,used,3,25,349,...,1.0,11,0,boy,734,1,price,0,0,0
22,54663,313.0,75750,private,2,0.0,new,1,15,287,...,0.0,10,8713,0,1157,1,price,0,0,5
23,57816,0.0,16853,private,11,0.0,used,0,400,260,...,1.0,1,0,0,714,1,arranged,0,0,48
24,59354,335.0,31762,private,4,0.0,used,18,60,102,...,2.0,2,0,woman,642,0,price,0,0,5
25,60344,1032.0,12345,private,6,0.0,0,1,50,83,...,1.0,1,0,0,1457,1,price,0,2,28
26,65228,0.0,26,private,4,0.0,used,2,20,162,...,0.0,12,0,girl,734,0,price,1,0,0
27,65885,318.0,12345,private,6,0.0,used,8,20,83,...,0.0,29,1596,0,1161,1,price,0,0,19
28,70826,2559.0,562,business,2,0.0,0,7,229,333,...,1.0,1,0,0,235,1,price,0,0,311
29,71135,0.0,2857,private,3,0.0,0,3,15,124,...,2.0,1,38412,0,1273,1,price,0,0,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999969,2147418547,4489.0,1064,private,6,0.0,used,4,80,353,...,2.0,1,0,0,231,1,price,0,0,92
999970,2147418562,108.0,44,private,5,0.0,0,1,NaN,290,...,1.0,1,28616,0,243,1,free,0,1,354
999971,2147420640,0.0,7064,private,6,0.0,used,2,100,48,...,0.0,2,0,0,451,1,price,0,0,5
999972,2147421449,0.0,25278,private,7,0.0,new,2,50,136,...,1.0,1,0,0,292,1,price,0,0,1
999973,2147425938,339.0,32,private,6,0.0,0,0,800,126,...,1.0,1,0,0,1459,1,arranged,0,0,146
999974,2147426316,0.0,43,private,6,0.0,used,0,45,299,...,2.0,9,0,0,584,1,price,0,0,2
999975,2147430370,363.0,32,private,1,0.0,new,0,40,181,...,2.0,1,0,woman,219,1,price,0,0,1
999976,2147432435,0.0,1301,private,11,0.0,used,17,15,261,...,1.0,5,0,girl,230,1,price,0,0,13
999977,2147439182,0.0,9705,private,15,0.0,new,4,150,278,...,1.0,6,0,man,626,1,price,0,0,114
999978,2147442236,0.0,489,private,3,0.0,used,0,35,145,...,1.0,5,0,0,231,1,price,0,0,7
999979,2147442934,0.0,1645,business,1,0.0,new,1,11.9,304,...,1.0,14,6306,0,1195,1,price,0,0,2
999980,2147447275,0.0,13,private,17,0.0,0,4,2.5,128,...,1.0,2,0,0,761,1,price,0,0,15
999981,2147452540,0.0,11458,private,18,0.0,used,24,20,9,...,2.0,11,0,girl,230,1,price,0,0,8
999982,2147453827,0.0,1733,private,12,0.0,new,4,35,85,...,1.0,5,0,unisex,406,1,price,0,0,0
999983,2147455249,0.0,2086,private,1,0.0,used,3,50,96,...,2.0,2,0,woman,224,1,price,0,0,0
999984,2147456174,840.0,2851,private,6,0.0,used,5,35,74,...,1.0,3,0,man,642,1,price,0,0,4
999985,2147458298,0.0,1879,private,6,0.0,used,26,70,214,...,0.0,3,0,girl,734,1,arranged,0,0,48
999986,2147458559,0.0,9529,private,14,0.0,used,4,160,171,...,2.0,7,0,woman,224,1,price,0,0,2
999987,2147458692,0.0,31762,private,4,0.0,used,0,20,102,...,2.0,10,0,woman,642,1,price,0,0,0
999988,2147460472,19678.0,25278,private,7,0.0,used,1,4,136,...,1.0,1,1596,0,1161,1,price,0,0,0
999989,2147463270,0.0,275,private,12,0.0,used,3,12,485,...,1.0,10,0,girl,230,1,price,0,0,2
999990,2147463747,1644.0,1998,business,5,0.0,new,4,29,276,...,1.0,13,0,boy,230,1,price,0,0,7
999991,2147465190,337.0,30524,private,3,0.0,0,0,1200,303,...,0.0,5,0,0,431,1,price,0,0,47
999992,2147465638,4569.0,2,private,18,0.0,0,0,25,429,...,2.0,1,0,0,761,1,price,0,0,10
999993,2147466167,0.0,84,private,3,0.0,used,0,15,49,...,1.0,4,0,girl,734,1,price,0,0,1
999994,2147468813,0.0,2857,private,3,0.0,used,5,15,124,...,1.0,10,0,girl,230,1,price,0,0,3
999995,2147470370,15623.0,459,private,14,0.0,used,0,22,15,...,1.0,2,0,woman,642,1,arranged,0,0,7
999996,2147470996,0.0,6075,private,11,0.0,used,5,30,98,...,1.0,8,0,woman,642,1,price,0,0,19
999997,2147479668,1007.0,882,business,6,0.0,new,6,35,373,...,1.0,20,0,girl,230,1,price,0,0,2
999998,2147481575,0.0,29,private,1,0.0,used,3,1190,220,...,1.0,10,113386,0,721,1,price,0,0,21

In [15]:
# Importing the libraries
import numpy as np
import pandas as pd

In [ ]:

# Importing the dataset
X = dataset.iloc[:, :-3].values
y = dataset.iloc[:, -3].values

# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
onehotencoder = OneHotEncoder()

In [17]:
# Importing the dataset
X = data.iloc[:, :-3].values
y = data.iloc[:, -3].values

In [18]:
categorical=[2,3,4,5,8,10,13,14,15]
X_temp = np.apply_along_axis(str,1,X[:,5])

AxisError: axis 1 is out of bounds for array of dimension 1

In [19]:
np.apply_along_axis(str,1,np.array(X[:,5]))

AxisError: axis 1 is out of bounds for array of dimension 1

In [20]:
X_temp = np.array(X[:,3]).reshape((999999,1))
X_temp = np.apply_along_axis(str,1,X_temp)

In [22]:
X[:,2]=labelencoder_X.fit_transform(X[:,2])
X[:,3]=labelencoder_X.fit_transform(X[:,3])
X[:,4]=labelencoder_X.fit_transform(X[:,4])
X[:,5]=labelencoder_X.fit_transform(X_temp)
X[:,8]=labelencoder_X.fit_transform(X[:,8])
X[:,10]=labelencoder_X.fit_transform(X[:,10])
X[:,13]=labelencoder_X.fit_transform(X[:,13])
X[:,14]=labelencoder_X.fit_transform(X[:,14])
X[:,15]=labelencoder_X.fit_transform(X[:,15])

TypeError: '<' not supported between instances of 'float' and 'str'

In [85]:
X_train = onehotencoder.fit_transform(X).toarray()

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
X[:,1]=np.apply_along_axis(str, 0, X[:,1])
set(X[:,1])

In [101]:
X[:,X[:,15]!='exchange']

IndexError: boolean index did not match indexed array along dimension 1; dimension is 16 but corresponding boolean dimension is 999999

In [99]:
X[:,15]!='exchange'

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [94]:
np.isnan(X)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [86]:
data.isnull().values.ravel().sum()

22573

array([['1473.0', '809', 1, ..., 250, 2, 4],
       ['680.0', '23', 1, ..., 205, 1, 4],
       ['0.0', '10', 1, ..., 2, 1, 2],
       ...,
       ['0.0', '6075', 1, ..., 205, 2, 4],
       ['1007.0', '882', 0, ..., 130, 2, 4],
       ['0.0', '29', 1, ..., 233, 2, 4]], dtype=object)

In [135]:
X = X[X[:,15]!=2]

In [145]:
sum(X[:,15]==3)

10419

In [137]:
type(X)
X.shape
np.nansum(X)

TypeError: must be str, not int

In [147]:
pandas_data = pd.DataFrame(X)
pandas_data.shape
pandas_data.columns.values.tolist()
pandas_data = pandas_data.fillna(0)
# pandas_data.shape
pandas_data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1473.0,809,1,0,0,2,2,13,105,2,2,6,8842,250,2,4
1,680.0,23,1,6,0,1,34,20,192,3,1,23,0,205,1,4
2,0.0,555,0,8,0,2,4,40,289,1,1,26,0,258,2,4
3,2493.0,3743,0,0,0,2,8,899,90,8,1,6,105036,23,2,4
4,459.0,25278,1,13,0,0,0,40,41,2,2,2,0,132,2,4
5,0.0,1001,1,3,0,1,1,15,152,2,1,2,0,77,2,4
6,0.0,471,1,11,0,2,3,65,124,4,1,6,57374,237,2,1
7,0.0,1817,1,14,0,2,4,18,125,1,2,11,0,130,1,4
8,0.0,1063,0,12,0,1,28,79,122,2,1,4,0,192,2,4
9,1341.0,4994,1,2,0,1,1,189,84,7,0,8,0,192,1,4
10,0.0,890,1,0,0,1,0,60,74,2,0,4,0,184,1,4
11,0.0,4241,1,9,0,2,5,60,15,1,1,1,0,205,2,4
12,0.0,79,1,1,0,1,6,40,191,3,1,5,0,205,2,4
13,429.0,7540,1,6,0,2,4,40,141,1,1,1,0,244,2,4
14,0.0,16853,1,1,0,1,4,50,178,2,1,2,0,157,2,4
15,1007.0,2844,0,14,0,1,3,43,235,4,1,83,0,192,2,4
16,0.0,19087,0,11,0,1,5,149,328,2,1,2,0,187,2,4
17,0.0,8,1,6,0,2,28,70,285,3,1,1,0,132,2,4
18,0.0,11458,1,7,0,0,40,20,405,3,2,2,0,132,2,4
19,0.0,25,1,4,0,2,108,30,316,5,0,6,0,244,2,4
20,337.0,1431,1,12,0,2,3,25,266,4,1,11,0,244,2,4
21,313.0,75750,1,8,0,1,1,15,207,2,0,10,8713,3,2,4
22,0.0,16853,1,1,0,2,0,400,178,3,1,1,0,227,2,1
23,335.0,31762,1,10,0,2,18,60,4,5,2,2,0,205,1,4
24,1032.0,12345,1,12,0,0,1,50,398,0,1,1,0,86,2,4
25,0.0,26,1,10,0,2,2,20,70,3,0,12,0,244,1,4
26,318.0,12345,1,12,0,2,8,20,398,3,0,29,1596,5,2,4
27,2559.0,562,0,8,0,0,7,229,257,4,1,1,0,132,2,4
28,0.0,2857,1,9,0,0,3,15,28,0,2,1,38412,35,2,4
29,355.0,75750,1,8,0,2,77,20,207,2,1,19,0,130,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987819,4489.0,1064,1,12,0,2,4,80,269,6,2,1,0,131,2,4
987820,108.0,44,1,11,0,0,1,0,211,6,1,1,28616,140,2,3
987821,0.0,7064,1,12,0,2,2,100,345,3,0,2,0,186,2,4
987822,0.0,25278,1,13,0,1,2,50,41,1,1,1,0,158,2,4
987823,339.0,32,1,12,0,0,0,800,30,7,1,1,0,87,2,1
987824,0.0,43,1,12,0,2,0,45,220,1,2,9,0,200,2,4
987825,363.0,32,1,0,0,1,0,40,91,2,2,1,0,128,2,4
987826,0.0,1301,1,1,0,2,17,15,179,1,1,5,0,130,2,4
987827,0.0,9705,1,5,0,1,4,150,197,5,1,6,0,204,2,4
987828,0.0,489,1,9,0,2,0,35,51,3,1,5,0,131,2,4
987829,0.0,1645,0,0,0,1,1,11.9,227,1,1,14,6306,21,2,4
987830,0.0,13,1,6,0,0,4,2.5,32,3,1,2,0,252,2,4
987831,0.0,11458,1,7,0,2,24,20,405,3,2,11,0,130,2,4
987832,0.0,1733,1,2,0,1,4,35,400,1,1,5,0,184,2,4
987833,0.0,2086,1,0,0,2,3,50,412,3,2,2,0,129,2,4
987834,840.0,2851,1,12,0,2,5,35,388,7,1,3,0,205,2,4
987835,0.0,1879,1,12,0,2,26,70,128,5,0,3,0,244,2,1
987836,0.0,9529,1,4,0,2,4,160,80,4,2,7,0,129,2,4
987837,0.0,31762,1,10,0,2,0,20,4,1,2,10,0,205,2,4
987838,19678.0,25278,1,13,0,2,1,4,41,1,1,1,1596,5,2,4
987839,0.0,275,1,2,0,2,3,12,348,1,1,10,0,130,2,4
987840,1644.0,1998,0,11,0,1,4,29,195,1,1,13,0,130,2,4
987841,337.0,30524,1,9,0,0,0,1200,226,6,0,5,0,185,2,4
987842,4569.0,2,1,7,0,0,0,25,315,0,2,1,0,252,2,4
987843,0.0,84,1,9,0,2,0,15,351,6,1,4,0,244,2,4
987844,0.0,2857,1,9,0,2,5,15,28,1,1,10,0,130,2,4
987845,15623.0,459,1,4,0,2,0,22,56,4,1,2,0,205,2,1
987846,0.0,6075,1,1,0,2,5,30,414,4,1,8,0,205,2,4
987847,1007.0,882,0,12,0,1,6,35,281,2,1,20,0,130,2,4
987848,0.0,29,1,0,0,2,3,1190,135,1,1,10,113386,233,2,4

In [116]:
pandas_data.isnull().values.ravel().sum()

22569

In [148]:
X_train = pandas_data.iloc[:, :].values

In [4]:
pandas_data.to_csv('data_train.csv',sep=';', index= False)

NameError: name 'pandas_data' is not defined